Add index
loriculberson/to-delete-project pull request #4
Opened 2024-05-08 23:55 UTC by loriculberson

New index file shows the new layout

2024-05-08 23:57 UTC, laxsonii requested changes
nice

2024-05-08 23:59 UTC, nducklow requested changes
Looks great!

2024-05-08 23:59 UTC, nducklow commented on index.html
> +    <h2>Hi</h2>
This should say Dunkin

2024-05-08 23:59 UTC, laxsonii requested changes

2024-05-08 23:59 UTC, laxsonii commented on index.html
> +</html>
change title

2024-05-08 23:59 UTC, laxsonii commented on index.html
> +</head>
add a new div

2024-05-09 00:01 UTC, loriculberson commented on index.html
> +    <h2>Hi</h2>
Fixed!

2024-05-09 00:01 UTC, loriculberson commented on index.html
> +</html>
changed title

2024-05-09 00:04 UTC, laxsonii approved these changes
thank you

2024-05-09 00:05 UTC, nducklow approved these changes

2024-05-09 00:06 UTC, merged